version: '3.8'

services:
  php-fpm:
    image: ${REGISTRY}/${INDEX}-php-fpm:${IMAGE_TAG}
    volumes:
      - ./:/var/www/html

  php-cli:
    image: ${REGISTRY}/${INDEX}-php-cli:${IMAGE_TAG}
    volumes:
      - ./:/app

  nginx:
    image: ${REGISTRY}/${INDEX}-nginx:${IMAGE_TAG}
    ports:
      - ${APP_WEB_PORT}:80
      - 6001:6001
    volumes:
      - ./:/var/www/html

  app-nodejs:
    image: ${REGISTRY}/${INDEX}-nodejs:${IMAGE_TAG}
    restart: "unless-stopped"
    environment:
      MODE: '${ENV}'
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "25m"
    ports:
      - 8000:8000
    entrypoint: /bin/sh
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true

  ollama:
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0


  postgres:
    image: pgvector/pgvector:pg17
    volumes:
      - pgsql:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=utf8 --lc-collate=C --lc-ctype=C
      - POSTGRES_DB=${DB_DATABASE}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 54321:5432
volumes:
  pgsql:
