services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/dockerfile
      target: fpm
    image: ${REGISTRY}/${INDEX}-php-fpm:${IMAGE_TAG}
    volumes:
      - ./:/var/www/html

  php-cli:
    image: ${REGISTRY}/${INDEX}-php-cli:${IMAGE_TAG}
    volumes:
      - ./:/app
    command: php artisan config:clear && php artisan cache:clear

  nginx:
    image: ${REGISTRY}/${INDEX}-nginx:${IMAGE_TAG}
    ports:
      - ${APP_WEB_PORT}:80
      - 6001:6001
    volumes:
      - ./:/var/www/html
    depends_on:
      - nodejs
    environment:
      - NGINX_CACHE_CONTROL="no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"

  nodejs:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: nodejs
    ports:
      - "5173:5173"  # Порт для Vite
    volumes:
      - ./:/app
    command: "npm run dev"

  ollama:
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  


  postgres:
    image: pgvector/pgvector:pg17
    volumes:
      - pgsql:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=utf8 --lc-collate=C --lc-ctype=C
      - POSTGRES_DB=${DB_DATABASE}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 54321:5432

volumes:
  pgsql:
