services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/dockerfile
      target: fpm
    image: ${REGISTRY}/${INDEX}-php-fpm:${IMAGE_TAG}
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  php-cli:
    image: ${REGISTRY}/${INDEX}-php-cli:${IMAGE_TAG}
    volumes:
      - ./:/app
    command: php artisan config:clear && php artisan cache:clear
    networks:
      - app-network

  nginx:
    image: ${REGISTRY}/${INDEX}-nginx:${IMAGE_TAG}
    ports:
      - ${APP_WEB_PORT}:80
      - 6001:6001
    volumes:
      - ./:/var/www/html
    depends_on:
      - nodejs
    environment:
      - NGINX_CACHE_CONTROL="no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: nodejs
    ports:
      - "5173:5173"  # Порт для Vite
    volumes:
      - ./:/app
    command: "npm run dev"
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - app-network


  postgres:
    image: pgvector/pgvector:pg17
    volumes:
      - pgsql:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=utf8 --lc-collate=C --lc-ctype=C
      - POSTGRES_DB=${DB_DATABASE}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 54321:5432
    networks:
      - app-network

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./python:/usr/src/app
      - ./python/venv:/usr/src/app/venv
    entrypoint: [ "./venv/bin/uvicorn" ]
    command: [ "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    environment:
      - FASTAPI_APP=app:app
      - ENV=development
    networks:
      - app-network


volumes:
  pgsql:

networks:
  app-network:
    driver: bridge
